import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRef } from "react";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  const myRef = useRef(null);

  return (
    <div className="snap max-h-screen snap-y snap-mandatory overflow-y-scroll">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="">
        <section className="relative mt-16 flex h-screen snap-start items-center justify-center overflow-hidden font-bold">
          <div className="relative z-30 mx-12 flex flex-col items-center justify-center bg-gray-50 bg-opacity-80 p-12 text-center text-4xl md:text-4xl xl:text-6xl">
            <span className="p-1 text-black">Wizualizacje</span>
            <span className="hero-text-gradient">dla Twojej firmy.</span>
            <div>
              <Link href="" passHref>
                <a className="hero-cta">Wchodzę w to!</a>
              </Link>
            </div>
          </div>
          <video className="video-section" autoPlay loop muted playsInline>
            <source src="/truulo_reel.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
        </section>
        <section
          id="o-nas"
          className="flex h-screen snap-start flex-col text-justify md:flex-row"
        >
          <div className="relative h-1/2 md:h-screen md:w-1/2">
            <Image
              alt="City image"
              layout="fill"
              objectFit="cover"
              src="https://images.unsplash.com/photo-1519501025264-65ba15a82390?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80"
            />
          </div>
          <div className="order-first h-1/2 bg-brandLightPink-100 px-2 pt-6 md:h-screen md:w-1/2 md:px-12 xl:pt-20">
            <h1 className="text-2xl">O nas</h1>
            <p className="pt-6 text-justify	">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Recusandae illo possimus inventore accusamus! Eius vitae sed,
              quaerat magni voluptatum quisquam reiciendis dolorem dignissimos
              similique ad sapiente ipsam neque consequatur eos. Lorem ipsum
              dolor sit amet consectetur, adipisicing elit. Recusandae illo
              possimus inventore accusamus! Eius vitae sed, quaerat magni
              voluptatum quisquam reiciendis dolorem dignissimos similique ad
              sapiente ipsam neque consequatur eos.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
