import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex "></main>
      <section className="h-screen">
        <video autoPlay loop muted width="100%">
          <source src="/truulo_reel.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <div
          style={{ position: "relative", width: "100%", paddingBottom: "20%" }}
        >
          {/* <Image
            alt="Main image"
            layout="fill"
            objectFit="contain"
            src={
              "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1794&q=80"
            }
          /> */}
        </div>
      </section>
    </div>
  );
};

export default Home;
